"""Add column from vlad

Revision ID: 27c53e209b22
Revises: 0eee520b247e
Create Date: 2022-01-16 14:31:39.771569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27c53e209b22'
down_revision = 'a2d4e9837dc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('col_from_vlad_dev', sa.String(length=50), nullable=True))
    op.drop_column('user', 'col_from_nikita_dev')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('col_from_nikita_dev', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('user', 'col_from_vlad_dev')
    # ### end Alembic commands ###
